spring:
    datasource:
        url: jdbc:mariadb://localhost:23304/howoo_training
        username: training
        password: training7698
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate.cache.region_prefix: local

logging:
    level:
        root: INFO
        web: DEBUG
        com.howoocast: DEBUG

server:
    port: 8080